/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardTrackingRouteImport } from './routes/dashboard.tracking'
import { Route as DashboardSummaryRouteImport } from './routes/dashboard.summary'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard.payments'
import { Route as DashboardUsersUserIdRouteImport } from './routes/dashboard.users_.$userId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTrackingRoute = DashboardTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSummaryRoute = DashboardSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersUserIdRoute = DashboardUsersUserIdRouteImport.update({
  id: '/users_/$userId',
  path: '/users/$userId',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/summary': typeof DashboardSummaryRoute
  '/dashboard/tracking': typeof DashboardTrackingRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/users/$userId': typeof DashboardUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/summary': typeof DashboardSummaryRoute
  '/dashboard/tracking': typeof DashboardTrackingRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/users/$userId': typeof DashboardUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/summary': typeof DashboardSummaryRoute
  '/dashboard/tracking': typeof DashboardTrackingRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/users_/$userId': typeof DashboardUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/payments'
    | '/dashboard/summary'
    | '/dashboard/tracking'
    | '/dashboard/users'
    | '/dashboard/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/payments'
    | '/dashboard/summary'
    | '/dashboard/tracking'
    | '/dashboard/users'
    | '/dashboard/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/payments'
    | '/dashboard/summary'
    | '/dashboard/tracking'
    | '/dashboard/users'
    | '/dashboard/users_/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tracking': {
      id: '/dashboard/tracking'
      path: '/tracking'
      fullPath: '/dashboard/tracking'
      preLoaderRoute: typeof DashboardTrackingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/summary': {
      id: '/dashboard/summary'
      path: '/summary'
      fullPath: '/dashboard/summary'
      preLoaderRoute: typeof DashboardSummaryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users_/$userId': {
      id: '/dashboard/users_/$userId'
      path: '/users/$userId'
      fullPath: '/dashboard/users/$userId'
      preLoaderRoute: typeof DashboardUsersUserIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardSummaryRoute: typeof DashboardSummaryRoute
  DashboardTrackingRoute: typeof DashboardTrackingRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardUsersUserIdRoute: typeof DashboardUsersUserIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardSummaryRoute: DashboardSummaryRoute,
  DashboardTrackingRoute: DashboardTrackingRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardUsersUserIdRoute: DashboardUsersUserIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
